name: Deploy Full Stack App

on:
  push:
    branches:
      - main
   workflow_dispatch:
jwobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd ~/Exilieen_full_stack/backend
            ./deploy_backend.sh

            cd ~/Exilieen_full_stack/frontend
            ./deploy_frontend.sh
